name: On Push

# On push to a "special" branch, we:
# * always publish to charmhub at latest/edge/branchname
# * always run tests
# where a "special" branch is one of main/master or track/**, as
# by convention these branches are the source for a corresponding
# charmhub edge channel.

on:
 push:
   branches:
     - main
     - track/**

jobs:
  test:
    name: test-charmcraft-pack
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.source_branch }}

      - name: Setup lxd
        uses: canonical/setup-lxd@v0.1.2
        with:
           channel: latest/stable
          
      # # Required to charmcraft pack in non-destructive mode
      # - name: Install and initialize lxd
      #   id: install-lxd
      #   run: |
      #     /usr/bin/sudo snap install core
      #     /usr/bin/sudo snap install lxd --channel=latest/stable
      #     /usr/bin/sudo lxd waitready
      #     /usr/bin/sudo lxd init --auto
      #     # /usr/bin/sudo chmod a+wr /var/snap/lxd/common/lxd/unix.socket
      #     # /snap/bin/lxc network set lxdbr0 ipv6.address none
      #     # /usr/bin/sudo usermod -a -G lxd runner
      #     /usr/bin/sudo iptables -F FORWARD
      #     /usr/bin/sudo iptables -P FORWARD ACCEPT
      
      # Dry run, without publishing
      - name: Charmcraft pack
        id: pack
        run: |
          /usr/bin/sudo snap install charmcraft --classic --channel latest/stable
          /usr/bin/sudo charmcraft pack --quiet

#  tests:
#    name: Run Tests
#    uses: ./.github/workflows/tests.yaml
#    secrets:
#      charmcraft-credentials: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
