on:
  schedule:
    - cron: '01 12 * * MON'

jobs:
  update-charm-libs:
    name: Update Charm Libraries
    uses: ./.github/workflows/update_libs.yaml
    secrets:
      CHARMCRAFT_CREDENTIALS: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
