name: Test workflow inputs conditions

on:
  workflow_call:
    inputs:
      charm_name:
        description: Name of the charmed application the tests are running for
        required: false
        type: string
      charmcraft-channel:
        description: Snap channel for charmcraft
        required: false
        default: latest/stable
        type: string
      use-charmcraftcache:
        description: Enable usage of charmcraftcache
        required: false
        default: false
        type: boolean
      
    outputs:
      name:
        description: The charm name
        value: ${{ jobs.build.outputs.name }}
      platforms:
        description: The platforms for which the charm has been built
        value: ${{ jobs.build.outputs.platforms }}
      charm-paths:
        description: The paths to all the charms built
        value: ${{ jobs.build.outputs.paths }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    outputs:
      name: ${{ steps.get-charm-info.outputs.charm-name }}
      platforms: ${{ steps.get-charm-info.outputs.charm-platforms }}
      paths: ${{ steps.get-charm-paths.outputs.charm-paths }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get workspace
        run: echo $GITHUB_WORKSPACE

      - name: Get inputs
        if: ${{ inputs.charm_name }}
        run: echo ${{ inputs.charm_name }}

      - name: Setup lxd
        uses: canonical/setup-lxd@v0.1.2
        with:
          channel: latest/stable

      - name: Install charmcraft
        run: |
          sudo snap install charmcraft --classic --channel ${{ inputs.charmcraft-channel }}
          echo CHARMCRAFT_BIN=charmcraft >> $GITHUB_ENV

      - name: Install charmcraftcache
        if: ${{ inputs.use-charmcraftcache }}
        run: |
          pipx install charmcraftcache
          echo CHARMCRAFT_BIN=ccc >> $GITHUB_ENV

      - name: Build charm
        run: ${{ env.CHARMCRAFT_BIN}} pack -v

      - name: Get charm info
        id: get-charm-info
        run: |
          echo charm-name=$(cat charmcraft.yaml | yq '.name') >> $GITHUB_OUTPUT
          echo charm-platforms=$(cat charmcraft.yaml | yq '.platforms | keys | tojson') >> $GITHUB_OUTPUT

      - name: Get charm paths
        id: get-charm-paths
        run: |
          echo charm-paths=$(echo '${{ steps.get-charm-info.outputs.charm-platforms }}' | jq -r --arg charm ${{ steps.get-charm-info.outputs.charm-name }} '.[] |= split(":") | .[] |= join("-", .) | map($charm + "_" + . + ".charm") | join(",")') >> $GITHUB_OUTPUT
          echo charm-paths

      - name: Get build path
        run: |
          echo $GITHUB_OUTPUT
          ls -la $GITHUB_WORKSPACE | grep charm
          echo "${{ GITHUB_WORKSPACE }}/${{ charm-paths }}
  set-env:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - name: Set CHARM_PATH envvar
        run: |
          echo "CHARM_PATH=${{ needs.test.outputs.paths }}" >> $GITHUB_ENV
          echo $CHARM_PATH
