name: test

on:
   workflow_dispatch:
   push:
     branches:
     - "main"

jobs:
  tests:
    name: Test callable workflow
    uses: ./.github/workflows/test-get-input.yaml
    with:
      use-charmcraftcache: true
