# Test push on path - check if action is triggered
name: Test push on path

on:
  push:
    branches:
      - main
    paths:
      - "integration-requirements.txt"

jobs:
  publish-lib:
    name: Test push on path
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install charmcraft
        run: sudo snap install charmcraft --channel latest/stable --classic
