on: [push]

jobs:
  fail_test:
    runs-on: ubuntu-latest
    name: A job that fails
    steps:
      - uses: actions/checkout@v2
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          channel: 1.25-strict/stable
      - name: Export microk8s config
        run: |
          mkdir -p ~/.kube
          newgrp snap_microk8s
          sudo usermod -a -G snap_microk8s $USER
          sg snap_microk8s -c microk8s config > ~/.kube/config
      - name: Deploy a charm
        run: juju deploy hello-kubecon
      - name: Fail
        run: "false"
      - name: Get groups
        run: groups
        if: failure()
      - name: Check config view
        run: kubectl config view
        if: failure()
      - name: Get microk8s config view
        run: microk8s config
        if: failure()
      - name: Dump logs
        uses: canonical/charm-logdump-action@HEAD
        if: failure()
        with:
          app: hello-kubecon
