# reusable workflow for checking library versions and opening PRs to bump
name: Update Charm Libraries

on:
  workflow_call:
    inputs:
      charmcraft_channel:
        description: Channel from which to install charmcraft
        default: 'latest/candidate'
        required: false
        type: string
    secrets:
      CHARMCRAFT_CREDENTIALS:
        required: true
  workflow_dispatch:
    inputs:
      charmcraft_channel:
        description: Channel from which to install charmcraft
        default: 'latest/candidate'
        required: false
        type: string

jobs:
  update-libs:
    name: Update charm libraries
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: sudo snap install charmcraft --channel ${{ inputs.charmcraft_channel }} --classic

      - name: update charm libs
        run: charmcraft fetch-lib
        env:
          CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_CREDENTIALS }}

      - name: Create Pull Request
        # permissions: write-all
        id: create-pull-request
        uses: canonical/create-pull-request@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Test commit message
          branch-name: 'automated-update-charm-libs-test'
          title: Test pull request
          body: Test pull request body
          ignore-no-changes: true
